export const projects = [
  {
    title: "E-Commerce Admin",
    tools: ["Nextjs", "Typescript", "Tailwind", "Clerk", "Stripe"],
    image: "/e-commerce-admin.png",
    link: "https://fab-ecommerce-admin.vercel.app/",
    code: "https://github.com/Fables7/ecommerce-admin",
  },
  {
    title: "E-Commerce Store",
    tools: ["Nextjs", "Typescript", "Tailwind", "Clerk", "Stripe"],
    image: "/e-commerce-store.png",
    link: "https://fab-ecommerce-store.vercel.app/",
    code: "https://github.com/Fables7/ecommerce-store",
  },
  {
    title: "LMS",
    tools: ["Nextjs", "Typescript", "Tailwind", "Clerk", "Stripe"],
    image: "/lms.png",
    link: "https://lms-fab.vercel.app/",
    code: "https://github.com/Fables7/lms-fab",
  },
  {
    title: "Discord Clone",
    tools: ["Nextjs", "Typescript", "Tailwind", "Websockets"],
    image: "/discord-clone.png",
    link: "https://fab-discord-clone.up.railway.app/",
    code: "https://github.com/Fables7/discord-clone",
  },
  {
    title: "Figma Clone",
    tools: ["Nextjs", "Typescript", "Tailwind", "Liveblocks"],
    image: "/figma-clone.png",
    link: "https://figma-clone-ruby.vercel.app/",
    code: "https://github.com/Fables7/figma-clone",
  },
  {
    title: "AI Saas",
    tools: [
      "Nextjs",
      "Typescript",
      "Tailwind",
      "OpenAI",
      "Stripe",
      "Clerk",
      "Crisp",
      "MySQL",
    ],
    image: "/ai-saas.png",
    link: "https://fab-ai-saas.vercel.app/",
    code: "https://github.com/Fables7/ai-saas",
  },
  {
    title: "Crowd funding app (WIP)",
    tools: ["Solidity", "Vite", "Javascript", "Tailwind", "Metamask"],
    image: "/crowdfunding.png",
    link: "https://fab-crowd-funding.netlify.app/",
    code: "https://github.com/Fables7/crowdfunding",
  },
  {
    title: "Evently",
    tools: ["Nextjs", "TypeScript", "Tailwind", "MongoDB", "Clerk", "Stripe"],
    image: "/evently.png",
    link: "https://fab-event-platform.vercel.app/",
    code: "https://github.com/Fables7/evently",
  },
  {
    title: "Threads app",
    tools: ["Nextjs", "TypeScript", "Tailwind", "MongoDB", "Clerk"],
    image: "/threads-app.png",
    link: "https://threads-app-snowy-beta.vercel.app/",
    code: "https://github.com/Fables7/threads_app",
  },
  {
    title: "Issue Tracker",
    tools: ["NextJs", "TypeScript", "Tailwind", "SQL", "Prisma", "Planetscale"],
    image: "/issue-tracker.svg",
    link: "https://issue-tracker-delta-sage.vercel.app/",
    code: "https://github.com/Fables7/issue-tracker",
  },
  {
    title: "GitHub Search",
    tools: ["React", "TypeScript", "Tailwind"],
    image: "/github-search-thumbnail.jpeg",
    link: "https://fables7-github-search-user.netlify.app/",
    code: "https://github.com/Fables7/github-user-search-app",
  },
  {
    title: "Travel app (Frontend)",
    tools: ["Vite", "Javascript", "Tailwind"],
    image: "/travel-app.png",
    link: "https://travel-app-ui-ux.netlify.app/",
    code: "https://github.com/Fables7/travel_app",
  },
  {
    title: "Nike site (Frontend)",
    tools: ["Vite", "Javascript", "Tailwind"],
    image: "/nike-site.png",
    link: "https://fab-nike-site.netlify.app/",
    code: "https://github.com/Fables7/nike-site",
  },
  {
    title: "Memory Game",
    tools: ["React", "TypeScript", "Tailwind"],
    image: "/memory-game-thumbnail.webp",
    link: "https://fables7-memory-game.netlify.app/",
    code: "https://github.com/Fables7/memory-game",
  },
  {
    title: "Fridge App",
    tools: [
      "React-Native",
      "TypeScript",
      "CSS",
      "Node.js",
      "MongoDB",
      "express.js",
      "AWS",
    ],
    image: "/fridge-app.svg",
    link: "",
    code: "https://github.com/Fables7/Fridge-App",
  },
  {
    title: "Zinnia Block Explorer",
    tools: ["React", "TypeScript", "CSS", "Node.js"],
    image: "/zinnia-explorer.png",
    link: "https://docs.google.com/document/d/1bbqunPOIxZmCjEEuFb-6jWnLLic96_05yQiPcJ6MHX8/edit?usp=sharing",
    code: "",
  },
];

export const experiences = [
  { skill: "HTML", years: 3 },
  { skill: "CSS", years: 3 },
  { skill: "JavaScript", years: 3 },
  { skill: "TypeScript", years: 3 },
  { skill: "React", years: 3 },
  { skill: "React-Native", years: 3 },
  { skill: "Node.js", years: 2 },
  { skill: "MongoDB", years: 2 },
  { skill: "Solidity", years: 1 },
  { skill: "SQL", years: 1 },
];
